Still error after removing Tensorflow.Net
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'Tensorflow.KerasApi' threw an exception.
  Source=Tensorflow.Keras
  StackTrace:
   at Tensorflow.KerasApi.get_keras()
   at TensorFlowNet_Updated_GAN.MnistGAN.PrepareData() in C:\Users\darla\Downloads\TensorFlowNetUpdatedGAN-main (1)\TensorFlowNetUpdatedGAN-main\TensorFlowNet-Updated-GAN\TensorFlowNet-Updated-GAN\MnistGAN.cs:line 49
   at TensorFlowNet_Updated_GAN.MnistGAN.Run() in C:\Users\darla\Downloads\TensorFlowNetUpdatedGAN-main (1)\TensorFlowNetUpdatedGAN-main\TensorFlowNet-Updated-GAN\TensorFlowNet-Updated-GAN\MnistGAN.cs:line 40
   at TensorFlowNet_Updated_GAN.Program.Main(String[] args) in C:\Users\darla\Downloads\TensorFlowNetUpdatedGAN-main (1)\TensorFlowNetUpdatedGAN-main\TensorFlowNet-Updated-GAN\TensorFlowNet-Updated-GAN\Program.cs:line 15

  This exception was originally thrown at this call stack:
    Tensorflow.KerasApi.KerasApi()

Inner Exception 1:
TypeLoadException: Method 'SimpleRNN' in type 'Tensorflow.Keras.Layers.LayersApi' from assembly 'Tensorflow.Keras, Version=0.10.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' does not have an implementation.